
package xx.mx.uv.presupuesto.wsdl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "presupuestoPort", targetNamespace = "t4is.uv.mx/presupuesto")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PresupuestoPort {


    /**
     * 
     * @param solicitarPagoPresupuestoRequest
     * @return
     *     returns xx.mx.uv.presupuesto.wsdl.SolicitarPagoPresupuestoResponse
     */
    @WebMethod(operationName = "SolicitarPagoPresupuesto")
    @WebResult(name = "SolicitarPagoPresupuestoResponse", targetNamespace = "t4is.uv.mx/presupuesto", partName = "SolicitarPagoPresupuestoResponse")
    public SolicitarPagoPresupuestoResponse solicitarPagoPresupuesto(
        @WebParam(name = "SolicitarPagoPresupuestoRequest", targetNamespace = "t4is.uv.mx/presupuesto", partName = "SolicitarPagoPresupuestoRequest")
        SolicitarPagoPresupuestoRequest solicitarPagoPresupuestoRequest);

}
